/**
 * Generated by PluginGenerator 0.14.0 from webgme on Tue Apr 05 2016 10:31:11 GMT-0700 (MST).
 */

define([], function () {
    'use strict';
    return {
        'FCO': '/1',
        'Language': '/I',
        'Left': '/I/q',
        'Path': '/I/G',
        'Paths': '/I/f',
        'Prim_Mot_Connection': '/I/3',
        'PrimitiveMotion': '/I/H',
        'Right': '/I/E',
        'StateConstraint': '/o/L',
        'Straight': '/I/6',
        'TransitionConstraint': '/o/Y',
    };
});
