// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push(__dirname + '/../src/plugins');
config.addOn.basePaths.push(__dirname + '/../src/addons');
config.visualization.decoratorPaths.push(__dirname + '/../src/decorators');

config.addOn.enable = true;





// Visualizer descriptors

// Add requirejs paths
config.requirejsPaths = {
  'dsml-4-kidz': './src/common'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/dsml_4_kidz';
validateConfig(config);
module.exports = config;
